project_manager/config/routes.rb
ProjectManager::Application.routes.draw do
  resources :project_colors

  resources :zone_levels

  resources :machines

  resources :project_scopes

  resources :travel_restrictions

  resources :restrictions

  resources :supervisor_levels

  resources :skill_levels

  get "home/index"
  get "home/canvas"
  get "home/slider_test"

  resources :technicians

  match "zones/add" => "zones#add"
  match "zones/add_technician" => "zones#add_technician"
  match "zones/remove_technician" => "zones#remove_technician"

  resources :zones

  resources :project_types

  match "projects/add_technician" => "projects#add_technician"
  match "projects/remove_technician" => "projects#remove_technician"
  match "projects/event_drop" => "projects#event_drop"
  match "projects/event_resize" => "projects#event_resize"

  resources :projects

  get "home/picklists"
  get "home/json_feed"

  root :to => "home#index"

end

project_manager/app/models/machine.rb
class Machine < ActiveRecord::Base
end

project_manager/app/models/machines_zone.rb
class MachinesZone < ActiveRecord::Base
  
end

project_manager/app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :project_type
  belongs_to :project_color
  has_and_belongs_to_many :technicians
  has_and_belongs_to_many :project_scopes
  has_many :zones

  validates_presence_of :name
  validates_presence_of :project_type_id
  validates_uniqueness_of :name

  def self.json_feed(params)
    start_date = format_time Time.at(params[:start].to_i)
    end_date = format_time Time.at(params[:end].to_i)

    projects = Project.all(:conditions=>["start_date BETWEEN :start AND :end OR end_date BETWEEN :start AND :end", {:start=>start_date, :end=>end_date}], :include=>:project_color)

    json_projects = []

    for project in projects
      if project.project_color
        bg_color = project.project_color.background
        color = project.project_color.text
      else
        bg_color = "black"
        color = "white"
      end
      json_projects << {:start=>project.start_date.to_i, :end=>project.end_date.to_i, :allDay=>false,
                        :id=>"project_#{project.id.to_s}",:title=>project.name, :url=>"/projects/#{project.id.to_s}/edit",
                        :editable=>true, :source=>'', :technicians=>project.technician_list, :background_color=>bg_color, :color=>color}
    end
    return json_projects
  end

  def technician_list
    technicians.collect{|t| t.name}.join(' | ')
  end

  def self.format_time(time)
    return time.strftime("%Y-%m-%d")
  end

  def available_technicians
    if !technician_ids.empty?
      return Technician.all(:conditions=>["id NOT IN (?)", technician_ids])
    else
      return Technician.all
    end
  end

  def background_color
    if project_color
      return project_color.background
    end
    return "black"
  end

  def text_color
    if project_color
      return project_color.text
    end
    return "white"
  end

  def update_from_drop(params)
    delta = params[:day_delta].to_i
    update_attributes(:start_date=>start_date+delta.days,
                      :end_date=>end_date+delta.days)
  end

  def update_from_resize(params)
    delta = params[:day_delta].to_i
    update_attribute(:end_date, end_date+delta.days)
  end

  def selected_project_color
    if project_color
      pc = "#{project_color_id}:#{project_color.background.upcase}:#{project_color.text.upcase}"
    else
      pc = ""
    end
    return pc
  end
  
end

project_manager/app/models/project_color.rb
class ProjectColor < ActiveRecord::Base
end

project_manager/app/models/project_scope.rb
class ProjectScope < ActiveRecord::Base

  has_and_belongs_to_many :projects
  
end

project_manager/app/models/project_type.rb
class ProjectType < ActiveRecord::Base

  validates_uniqueness_of :description
  validates_presence_of :description

  def to_s
    description
  end
  
  def abbreviation
    description[0,1]
  end
end

project_manager/app/models/projects_technician.rb
class ProjectsTechnician < ActiveRecord::Base
  
end

project_manager/app/models/restriction.rb
class Restriction < ActiveRecord::Base

  has_many :technicians

  validates_presence_of :number
  validates_presence_of :description

  def value
    [number, description].join(': ')
  end

end

project_manager/app/models/skill_level.rb
class SkillLevel < ActiveRecord::Base
  validates_uniqueness_of :level
  validates_presence_of :level

  def to_s
    level
  end
end

project_manager/app/models/supervisor_level.rb
class SupervisorLevel < ActiveRecord::Base
  validates_uniqueness_of :level
  validates_presence_of :level

  def to_s
    level
  end
end

project_manager/app/models/technician.rb
class Technician < ActiveRecord::Base

  belongs_to :skill_level
  belongs_to :supervisor_level
  belongs_to :project_type
  has_and_belongs_to_many :projects
  belongs_to :restriction
  has_and_belongs_to_many :zones

  validates_presence_of :first_name
  validates_presence_of :last_name

  def name
    "#{last_name}, #{first_name} #{middle_initial}"
  end

  def abb
    "#{first_name[0,1]}#{last_name}"
  end
end

project_manager/app/models/technicians_zone.rb
class TechniciansZone < ActiveRecord::Base

  

end

project_manager/app/models/travel_restriction.rb
class TravelRestriction < ActiveRecord::Base
end

project_manager/app/models/zone.rb
class Zone < ActiveRecord::Base

  belongs_to :project
  belongs_to :zone_level
  has_and_belongs_to_many :technicians

  def zone_name
    name.blank? ? "(Not Provided)" : name
  end

end

project_manager/app/models/zone_level.rb
class ZoneLevel < ActiveRecord::Base

  has_many :zones

  def to_s
    level
  end

end

project_manager/app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  # GET /technicians
  # GET /technicians.xml
  def index
    @technicians = Technician.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @technicians }
    end
  end

  # GET /technicians/1
  # GET /technicians/1.xml
  def show
    @technician = Technician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @technician }
    end
  end

  # GET /technicians/new
  # GET /technicians/new.xml
  def new
    @technician = Technician.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @technician }
    end
  end

  # GET /technicians/1/edit
  def edit
    @technician = Technician.find(params[:id])
  end

  # POST /technicians
  # POST /technicians.xml
  def create
    @technician = Technician.new(params[:technician])

    respond_to do |format|
      if @technician.save
        format.html { redirect_to(@technician, :notice => 'Technician was successfully created.') }
        format.xml  { render :xml => @technician, :status => :created, :location => @technician }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @technician.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /technicians/1
  # PUT /technicians/1.xml
  def update
    @technician = Technician.find(params[:id])

    respond_to do |format|
      if @technician.update_attributes(params[:technician])
        format.html { redirect_to(@technician, :notice => 'Technician was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @technician.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /technicians/1
  # DELETE /technicians/1.xml
  def destroy
    @technician = Technician.find(params[:id])
    @technician.destroy

    respond_to do |format|
      format.html { redirect_to(technicians_url) }
      format.xml  { head :ok }
    end
  end
end

project_manager/app/helpers/application_helper.rb
module ApplicationHelper

  def f_date(date)
    if date
      return date.strftime("%x")
    end
  end

end

project_manager/app/helpers/home_helper.rb
module HomeHelper
end

project_manager/app/helpers/machines_helper.rb
module MachinesHelper
end

project_manager/app/helpers/projects_helper.rb
module ProjectsHelper
end

project_manager/app/helpers/technicians_helper.rb
module TechniciansHelper
end

project_manager/app/helpers/zone_levels_helper.rb
module ZoneLevelsHelper
end

project_manager/app/helpers/zones_helper.rb
module ZonesHelper
end

project_manager/app/views/technicians/_form.html.erb
<%= form_for(@technician) do |f| %>
  <% if @technician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technician.errors.count, "error") %> prohibited this technician from being saved:</h2>

      <ul>
      <% @technician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='one-third r-margin left'>
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :middle_initial %><br />
      <%= f.text_field :middle_initial %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :project_type_id %>
      <%= f.select(:project_type_id, ProjectType.all.collect{|s| [s.description, s.id]},
                   {:include_blank=>true},
                   {})%>
    </div>
    <div class="field">
      <%= f.label :skill_level_id %>
      <%= f.select(:skill_level_id, SkillLevel.all.collect{|s| [s.level, s.id]},
                   {:include_blank=>true},
                   {})%>
    </div>
    <div class="field">
      <%= f.label :supervisor_level_id %>
      <%= f.select(:supervisor_level_id, SupervisorLevel.all.collect{|s| [s.level, s.id]},
                   {:include_blank=>true},
                   {})%>
    </div>
    <div class="field">
      <%= f.label :restriction_id %>
      <%= f.select(:restriction_id, Restriction.all.collect{|s| [s.value, s.id]},
                   {:include_blank=>true},
                   {})%>
    </div>
    <div class="field">
      <%= f.label :lp_experience %>
      <%= f.check_box(:lp_experience)%>
    </div>
    <div class="field">
      <%= f.label :hp_experience %>
      <%= f.check_box(:hp_experience)%>
    </div>
    <div class="field">
      <%= f.label :generator_experience %>
      <%= f.check_box(:generator_experience)%>
    </div>
    <div class="field">
      <%= f.label :rotor_experience %>
      <%= f.check_box(:rotor_experience)%>
    </div>
    <div class="field">
      <%= f.label :rewind_experience %>
      <%= f.check_box(:rewind_experience)%>
    </div>
    <div class="field">
      <%= f.label :mat_experience %>
      <%= f.check_box(:mat_experience)%>
    </div>
    <div class="field">
      <%= f.label :bwr_experience %>
      <%= f.check_box(:bwr_experience)%>
    </div>
    <div class="field">
      <%= f.label :rca_experience %>
      <%= f.check_box(:rca_experience)%>
    </div>
    <div class="actions">
      <button class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Save</button>
    </div>
  </div>
  <div class='two-thirds r-margin left'>
    <div class="field">
      <%= f.label :compatability_notes %><br />
      <%= f.text_area :compatability_notes, :style=>'width:99%' %>
    </div>
    <div style='clear:both'></div>
    <div class="field">
      <%= f.label :travel_notes %><br />
      <%= f.text_area :travel_notes, :style=>'width:99%' %>
    </div>
    <div style='clear:both'></div>
    <div class="field">
      <%= f.label :work_capability_notes %><br />
      <%= f.text_area :work_capability_notes, :style=>'width:99%' %>
    </div>
  </div>
<% end %>

project_manager/app/views/technicians/edit.html.erb
<div class="ui-widget-content ui-corner-all form">
  <div class="ui-widget-header ui-corner-all">
    <h1>Editing technician</h1>
  </div>
  <br/>
  <%= render 'form' %>
  <div style='clear:both'></div>
</div>
<%= link_to 'Show', @technician %> |
<%= link_to 'Back', technicians_path %>

project_manager/app/views/technicians/index.html.erb
<div class="ui-widget-content ui-corner-all form">
  <div class="ui-widget-header ui-corner-all">
    <h1>Listing Technicians</h1>
  </div>

<table>
  <tr>
    <th>Name</th>
    <th>Project type</th>
    <th>Skill level</th>
    <th>Supervisor level</th>
    <th></th>
    <th></th>
  </tr>

<% @technicians.each do |technician| %>
  <tr>
    <td><%= technician.name %></td>
    <td><%= technician.project_type.to_s %></td>
    <td><%= technician.skill_level.to_s %></td>
    <td><%= technician.supervisor_level.to_s %></td>
    <td><%= link_to 'Show', technician %></td>
    <td><%= link_to 'Edit', edit_technician_path(technician) %></td>
  </tr>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Technician', new_technician_path %>

project_manager/app/views/technicians/new.html.erb
<div class="ui-widget-content ui-corner-all form">
  <div class="ui-widget-header ui-corner-all">
    <h1>New Technician</h1>
  </div>

<%= render 'form' %>

<%= link_to 'Back', technicians_path %>
</div>

project_manager/app/views/technicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @technician.name %>
</p>
<p>
  <b>Project type:</b>
  <%= @technician.project_type.to_s %>
</p>

<p>
  <b>Skill level:</b>
  <%= @technician.skill_level.to_s %>
</p>

<p>
  <b>Supervisor level:</b>
  <%= @technician.supervisor_level.to_s %>
</p>

<p>
  <b>Compatability notes:</b>
  <%= @technician.compatability_notes %>
</p>

<p>
  <b>Travel notes:</b>
  <%= @technician.travel_notes %>
</p>

<p>
  <b>Work capability notes:</b>
  <%= @technician.work_capability_notes %>
</p>


<%= link_to 'Edit', edit_technician_path(@technician) %> |
<%= link_to 'Back', technicians_path %>