project_manager/config/routes.rb
ProjectManager::Application.routes.draw do
  resources :project_colors

  resources :zone_levels

  resources :machines

  resources :project_scopes

  resources :travel_restrictions

  resources :restrictions

  resources :supervisor_levels

  resources :skill_levels

  get "home/index"
  get "home/canvas"
  get "home/slider_test"

  resources :technicians

  match "zones/add" => "zones#add"
  match "zones/add_technician" => "zones#add_technician"
  match "zones/remove_technician" => "zones#remove_technician"

  resources :zones

  resources :project_types

  match "projects/add_technician" => "projects#add_technician"
  match "projects/remove_technician" => "projects#remove_technician"
  match "projects/event_drop" => "projects#event_drop"
  match "projects/event_resize" => "projects#event_resize"

  resources :projects

  get "home/picklists"
  get "home/json_feed"

  root :to => "home#index"

end

project_manager/app/models/machine.rb
class Machine < ActiveRecord::Base
end

project_manager/app/models/machines_zone.rb
class MachinesZone < ActiveRecord::Base
  
end

project_manager/app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :project_type
  belongs_to :project_color
  has_and_belongs_to_many :technicians
  has_and_belongs_to_many :project_scopes
  has_many :zones

  validates_presence_of :name
  validates_presence_of :project_type_id
  validates_uniqueness_of :name

  def self.json_feed(params)
    start_date = format_time Time.at(params[:start].to_i)
    end_date = format_time Time.at(params[:end].to_i)

    projects = Project.all(:conditions=>["start_date BETWEEN :start AND :end OR end_date BETWEEN :start AND :end", {:start=>start_date, :end=>end_date}], :include=>:project_color)

    json_projects = []

    for project in projects
      if project.project_color
        bg_color = project.project_color.background
        color = project.project_color.text
      else
        bg_color = "black"
        color = "white"
      end
      json_projects << {:start=>project.start_date.to_i, :end=>project.end_date.to_i, :allDay=>false,
                        :id=>"project_#{project.id.to_s}",:title=>project.name, :url=>"/projects/#{project.id.to_s}/edit",
                        :editable=>true, :source=>'', :technicians=>project.technician_list, :background_color=>bg_color, :color=>color}
    end
    return json_projects
  end

  def technician_list
    technicians.collect{|t| t.name}.join(' | ')
  end

  def self.format_time(time)
    return time.strftime("%Y-%m-%d")
  end

  def available_technicians
    if !technician_ids.empty?
      return Technician.all(:conditions=>["id NOT IN (?)", technician_ids])
    else
      return Technician.all
    end
  end

  def background_color
    if project_color
      return project_color.background
    end
    return "black"
  end

  def text_color
    if project_color
      return project_color.text
    end
    return "white"
  end

  def update_from_drop(params)
    delta = params[:day_delta].to_i
    update_attributes(:start_date=>start_date+delta.days,
                      :end_date=>end_date+delta.days)
  end

  def update_from_resize(params)
    delta = params[:day_delta].to_i
    update_attribute(:end_date, end_date+delta.days)
  end

  def selected_project_color
    if project_color
      pc = "#{project_color_id}:#{project_color.background.upcase}:#{project_color.text.upcase}"
    else
      pc = ""
    end
    return pc
  end
  
end

project_manager/app/models/project_color.rb
class ProjectColor < ActiveRecord::Base
end

project_manager/app/models/project_scope.rb
class ProjectScope < ActiveRecord::Base

  has_and_belongs_to_many :projects
  
end

project_manager/app/models/project_type.rb
class ProjectType < ActiveRecord::Base

  validates_uniqueness_of :description
  validates_presence_of :description

  def to_s
    description
  end
  
  def abbreviation
    description[0,1]
  end
end

project_manager/app/models/restriction.rb
class Restriction < ActiveRecord::Base

  has_many :technicians

  validates_presence_of :number
  validates_presence_of :description

  def value
    [number, description].join(': ')
  end

end

project_manager/app/models/skill_level.rb
class SkillLevel < ActiveRecord::Base
  validates_uniqueness_of :level
  validates_presence_of :level

  def to_s
    level
  end
end

project_manager/app/models/supervisor_level.rb
class SupervisorLevel < ActiveRecord::Base
  validates_uniqueness_of :level
  validates_presence_of :level

  def to_s
    level
  end
end

project_manager/app/models/technician.rb
class Technician < ActiveRecord::Base

  belongs_to :skill_level
  belongs_to :supervisor_level
  belongs_to :project_type
  has_and_belongs_to_many :projects
  belongs_to :restriction
  has_and_belongs_to_many :zones

  validates_presence_of :first_name
  validates_presence_of :last_name

  def name
    "#{last_name}, #{first_name} #{middle_initial}"
  end

  def abb
    "#{first_name[0,1]}#{last_name}"
  end
end

project_manager/app/models/technicians_zone.rb
class TechniciansZone < ActiveRecord::Base

  

end

project_manager/app/models/travel_restriction.rb
class TravelRestriction < ActiveRecord::Base
end

project_manager/app/models/zone.rb
class Zone < ActiveRecord::Base

  belongs_to :project
  belongs_to :zone_level
  has_and_belongs_to_many :technicians

  def zone_name
    name.blank? ? "(Not Provided)" : name
  end

end

project_manager/app/models/zone_level.rb
class ZoneLevel < ActiveRecord::Base

  has_many :zones

  def to_s
    level
  end

end

project_manager/app/controllers/travel_restrictions_controller.rb
class TravelRestrictionsController < ApplicationController
  # GET /travel_restrictions
  # GET /travel_restrictions.xml
  def index
    @travel_restrictions = TravelRestriction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @travel_restrictions }
    end
  end

  # GET /travel_restrictions/1
  # GET /travel_restrictions/1.xml
  def show
    @travel_restriction = TravelRestriction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @travel_restriction }
    end
  end

  # GET /travel_restrictions/new
  # GET /travel_restrictions/new.xml
  def new
    @travel_restriction = TravelRestriction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @travel_restriction }
    end
  end

  # GET /travel_restrictions/1/edit
  def edit
    @travel_restriction = TravelRestriction.find(params[:id])
  end

  # POST /travel_restrictions
  # POST /travel_restrictions.xml
  def create
    @travel_restriction = TravelRestriction.new(params[:travel_restriction])

    respond_to do |format|
      if @travel_restriction.save
        format.html { redirect_to(@travel_restriction, :notice => 'Travel restriction was successfully created.') }
        format.xml  { render :xml => @travel_restriction, :status => :created, :location => @travel_restriction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @travel_restriction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /travel_restrictions/1
  # PUT /travel_restrictions/1.xml
  def update
    @travel_restriction = TravelRestriction.find(params[:id])

    respond_to do |format|
      if @travel_restriction.update_attributes(params[:travel_restriction])
        format.html { redirect_to(@travel_restriction, :notice => 'Travel restriction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @travel_restriction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /travel_restrictions/1
  # DELETE /travel_restrictions/1.xml
  def destroy
    @travel_restriction = TravelRestriction.find(params[:id])
    @travel_restriction.destroy

    respond_to do |format|
      format.html { redirect_to(travel_restrictions_url) }
      format.xml  { head :ok }
    end
  end
end

project_manager/app/helpers/application_helper.rb
module ApplicationHelper

  def f_date(date)
    if date
      return date.strftime("%x")
    end
  end

end

project_manager/app/helpers/home_helper.rb
module HomeHelper
end

project_manager/app/helpers/machines_helper.rb
module MachinesHelper
end

project_manager/app/helpers/projects_helper.rb
module ProjectsHelper
end

project_manager/app/helpers/technicians_helper.rb
module TechniciansHelper
end

project_manager/app/helpers/travel_restrictions_helper.rb
module TravelRestrictionsHelper
end

project_manager/app/helpers/zone_levels_helper.rb
module ZoneLevelsHelper
end

project_manager/app/helpers/zones_helper.rb
module ZonesHelper
end

project_manager/app/views/travel_restrictions/_form.html.erb
<%= form_for(@travel_restriction) do |f| %>
  <% if @travel_restriction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@travel_restriction.errors.count, "error") %> prohibited this travel_restriction from being saved:</h2>

      <ul>
      <% @travel_restriction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project_manager/app/views/travel_restrictions/edit.html.erb
<div class="ui-widget-content ui-corner-all form">
  <div class="ui-widget-header ui-corner-all">
    <h1>Editing Travel Restriction</h1>
  </div>

<%= render 'form' %>

<%= link_to 'Show', @travel_restriction %> |
<%= link_to 'Back', travel_restrictions_path %>
</div>

project_manager/app/views/travel_restrictions/index.html.erb
<div class="ui-widget-content ui-corner-all form">
  <div class="ui-widget-header ui-corner-all">
    <h1>Listing Travel Restrictions</h1>
  </div>

<table>
  <tr>
    <th>Number</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @travel_restrictions.each do |travel_restriction| %>
  <tr>
    <td><%= travel_restriction.number %></td>
    <td><%= travel_restriction.description %></td>
    <td><%= link_to 'Show', travel_restriction %></td>
    <td><%= link_to 'Edit', edit_travel_restriction_path(travel_restriction) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Travel restriction', new_travel_restriction_path %>
</div>

project_manager/app/views/travel_restrictions/new.html.erb
<div class="ui-widget-content ui-corner-all form">
  <div class="ui-widget-header ui-corner-all">
    <h1>New Travel Restriction</h1>
  </div>

<%= render 'form' %>

<%= link_to 'Back', travel_restrictions_path %>
</div>

project_manager/app/views/travel_restrictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @travel_restriction.number %>
</p>

<p>
  <b>Description:</b>
  <%= @travel_restriction.description %>
</p>


<%= link_to 'Edit', edit_travel_restriction_path(@travel_restriction) %> |
<%= link_to 'Back', travel_restrictions_path %>